stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/california_housing.csv
    - src/preprocess.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    outs:
    - models/rf_regression.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/test.csv
    - models/rf_regression.pkl
    - src/evaluate.py
    outs:
    - reports/metrics.json
